name: GitHub-Profile-3D-Contrib

on:
  schedule: # 00:00 KST == 15:00 UTC
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.README }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name larry
          git config user.email guyko91@gmail.com
          git remote set-url origin https://github.com/guyko91/guyko91.git
          git add -A .
          git commit -m "generated"
          git push https://$GITHUB_TOKEN@github.com/guyko91/guyko91.git
